# CS2-GUMAMELA
hello 🥶

## What does this code do?

This code helps with finding the distance between two points in a two-dimensional plane.

## How to run?

- Open the program file in VS Code, Replit, or Google Colab.

- Run the program.

- Enter the values for x1, y1, x2, and y2.

- Check the distance displayed on the screen.

##Input needed:
x1
x2
y1
y2
##Examples:

Enter point_x1. 8
Enter point_x2. 9
Enter y_1. 4
Enter point y_2. 7
Your distance is 3.1622776601683795

